---
title: "Timers for STA 210"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    css: "sta210-slides.css"
    lib_dir: libs/font-awesome
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%" 
      ratio: "16:9"
editor_options: 
  chunk_output_type: console
---

```{r child = "setup.Rmd"}
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(countdown)
```

```{r echo = F}
countdown(minutes = 1, seconds = 0,
          top = 0, bottom = 0,
          left = 0, right = 0,
          margin = "5%", 
          font_size = "6em")
```

---

```{r echo = F}
countdown(minutes = 3, seconds = 0,
          top = 0, bottom = 0,
          left = 0, right = 0,
          margin = "5%", 
          font_size = "6em")
```

---

```{r echo = F}
countdown(minutes = 5, seconds = 0,
          top = 0, bottom = 0,
          left = 0, right = 0,
          margin = "5%", 
          font_size = "6em")
```

---



```{r echo = F}
countdown(minutes = 8, seconds = 0,
          top = 0, bottom = 0,
          left = 0, right = 0,
          margin = "5%", 
          font_size = "6em")
```

